### ISSUE TITLE
Ruby Kanban Board Project Setup 

### ISSUE THREAD

**Issue by Johnadibe** [Johnadibe/catalog_of_my_things#9]
[Link to Project](https://github.com/Johnadibe/catalog_of_my_things/projects/1)

We are three members in this group:

- John Adibe @Johnadibe 
- Ochuba Chukwuemeka @Donmark2k 
- Shakir Hussain @Shakir-Hussain12

**Comment by m05e5** [comment]
Hi Team , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights

- Well done Creating the Kanban Board

## Required Changes ♻️
* You really did a great job creating the Kanban board with the different columns but there are some features you need to improve
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37901469/233962205-8ce84d15-9b82-40aa-955f-49eae943ae12.png">

- One of the main purposes of the Kanban board is to help subdivide big tasks into smaller tasks and from what I saw, you grouped all the tasks into big tasks per team member. Please as mentioned in the requirements, Kindly make sure to
    - [x] Split the big tasks into smaller tasks (You can use the bullet points present in each task description)
    - [ ] Give proper time allocation to each task (remember: 1hour = 1pt)
    - [ ] Give descriptive task title (Title should concern the part of the work you are supposed to do)
    - [ ] Make sure every task mentioned in your project requirement is in your Kanban board
    - [ ] After splitting the tasks please make sure every participant has approximately equal participation


_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Johnadibe** [comment]
Hello @m05e5, Thanks for the feedback. We have implemented the requested changes.

**Comment by Olamarx** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Equal distribution ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] I could not see anything as regards the schema file creation. Kindly add it to the tasks for each memeber.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Johnadibe** [comment]
Hello @Olamarx, Thanks for your feedback. I have implemented the requested changes.

**Comment by KDlamini** [comment]
### Hi team @Johnadibe, @Shakir-Hussain12, @Donmark2k 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes for the Ruby Kanban Board Project Setup. 🎊 🥳 
Your feature is complete!
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ The big tasks are split into smaller tasks 
✔️ There's proper time allocation to each task
✔️ All team members are allocated a task
✔️ Each task has a description and a task title

# Status: Approved ✔️ 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
